<a href="https://colab.research.google.com/github/antonellafontanetto/DataScience/blob/main/Notebook_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

## Analisis Exploratorio de un Dataset

Esta notebook les permitiria ejercitar los conceptos de Pandas üêº  y An√°lisis exploratorio de datos üìä que aprendimos hasta ahora. Vamos a trabajar con un dataset que contiene datos relativos a [clientes de un centro comercial](https://www.kaggle.com/akram24/mall-customers). En el Drive esta descargado el archivo. Si tenes inconvenientes o  ese archivo no funciona podes descargarlo directamente de la p√°gina web.

### üî¨ Comenzando el proyecto üéâ

Es tu primer dia como Data Scientist. Tu primer proyecto consiste en hacer un an√°lisis de datos sobre clientes de un centro comercial para luego hacer una predicci√≥n de ventas o un analisis de cluster. Antes que nada, debes inspeccionar y visualizar tu dataset para saber con que datos estas trabajando.

Como mencionamos durante la clase, una de las primeras cosas que debe realizar un Data Scientist al iniciar un nuevo proyecto es conocer el dataset con el cual va a trabajar. Este paso se conoce como _"Analisis exploratorio de los datos"_.

Adem√°s de obtener que tipo de datos contiene el dataset, estadistica descriptiva, detectar problemas como valores faltantes, establecer que tipo de relaci√≥n existe entre las distintas variables, tambi√©n debemos visualizar los datos. Este an√°lisis nos permitira hacernos preguntas que puedan ser contestadas con el dataset como as√≠ plantear estrategias para poder resolver problemas presentes en √©l.

#### IMPORTA LAS LIBRERIAS NECESARIAS

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

**_Lee los datos que se encuentran en el archivo `clientes_mall.csv`. Guardalos en un DataFrame._**

In [7]:
datos=pd.read_csv('/content/Thu H√† Tr·∫ßn - Mall_Customers.csv')
print(datos)

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

#### INSPECCIONA LOS DATOS

Primero obtene una visi√≥n general del dataset:


ü§î &nbsp; **_¬øComo se ven las primeras 5 filas? ¬øCuantas filas y columnas posee? ¬øQue tipos de datos contiene cada una de las columnas?_**

In [6]:
datos.head(5)

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [8]:
datos.shape

(200, 5)

In [9]:
datos.dtypes

CustomerID                 int64
Genre                     object
Age                        int64
Annual Income (k$)         int64
Spending Score (1-100)     int64
dtype: object

**_Hay algunas columnas que tienen nombres incomodos (ej. `Spending Score (1-100)` y `Annual Income (k$)`). Renombra esas columnas_**

In [16]:
datos.rename(columns= {'Annual income (k$)':'Ingresos','Spending Score (1-100)':'Spend'}, inplace=True)
datos.dtypes

CustomerID             int64
Genre                 object
Age                    int64
Annual Income (k$)     int64
Spend                  int64
dtype: object

In [11]:
datos.isnull().sum()

CustomerID                0
Genre                     0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

Elimina todas las filas que tengan

In [17]:
datos.dropna(inplace=True)
datos

     CustomerID   Genre  Age  Annual Income (k$)  Spend
0             1    Male   19                  15     39
1             2    Male   21                  15     81
2             3  Female   20                  16      6
3             4  Female   23                  16     77
4             5  Female   31                  17     40
..          ...     ...  ...                 ...    ...
195         196  Female   35                 120     79
196         197  Female   45                 126     28
197         198    Male   32                 126     74
198         199    Male   32                 137     18
199         200    Male   30                 137     83

[200 rows x 5 columns]

#### Valores faltantes

ü§î &nbsp; **_¬øHay valores faltantes en alguna de las columnas?_**

**_Elimina todas las filas que tengan valores faltantes_**

#### FILTRA LOS DATOS

Porque tu compa√±ia quiere dise√±ar un a campa√±a de marketing especial para personas entre 25 y 40 a√±os, vamos a analizar los datos solo para estos clientes.

ü§î &nbsp; **_Chequea que categorias aparecen en la columna `Age`_**.

In [18]:
datos['Age'].unique()

array([19, 21, 20, 23, 31, 22, 35, 64, 30, 67, 58, 24, 37, 52, 25, 46, 54,
       29, 45, 40, 60, 53, 18, 49, 42, 36, 65, 48, 50, 27, 33, 59, 47, 51,
       69, 70, 63, 43, 68, 32, 26, 57, 38, 55, 34, 66, 39, 44, 28, 56, 41])

In [20]:
edad=datos[(datos['Age']>=25) & (datos['Age']<=40)]
edad

     CustomerID   Genre  Age  Annual Income (k$)  Spend
4             5  Female   31                  17     40
6             7  Female   35                  18      6
9            10  Female   30                  19     72
11           12  Female   35                  19     99
14           15    Male   37                  20     13
..          ...     ...  ...                 ...    ...
193         194  Female   38                 113     91
195         196  Female   35                 120     79
197         198    Male   32                 126     74
198         199    Male   32                 137     18
199         200    Male   30                 137     83

[87 rows x 5 columns]

**_Filtra los datos para quedarte unicamente con las filas que correspondan a personas entre 25 y 40 a√±os. Guardalo en una variable que se llame `clientes_seleccionados`._**

In [21]:
clientes_seleccionados=datos[(datos['Age']>=25) & (datos['Age']<=40)]
clientes_seleccionados

     CustomerID   Genre  Age  Annual Income (k$)  Spend
4             5  Female   31                  17     40
6             7  Female   35                  18      6
9            10  Female   30                  19     72
11           12  Female   35                  19     99
14           15    Male   37                  20     13
..          ...     ...  ...                 ...    ...
193         194  Female   38                 113     91
195         196  Female   35                 120     79
197         198    Male   32                 126     74
198         199    Male   32                 137     18
199         200    Male   30                 137     83

[87 rows x 5 columns]

**_Reiniciamos el indice usando `reset_index()` para que las filas vuelvan a ser numeradas a partir de 0. `drop=True` permite descartar los indices anteriores y no guardarlos como una nueva columna. `inplace=True` permite que se modifique el DataFrame original._**

In [25]:
datos.reset_index(drop=True,inplace=True)
datos

     CustomerID   Genre  Age  Annual Income (k$)  Spend
0             1    Male   19                  15     39
1             2    Male   21                  15     81
2             3  Female   20                  16      6
3             4  Female   23                  16     77
4             5  Female   31                  17     40
..          ...     ...  ...                 ...    ...
195         196  Female   35                 120     79
196         197  Female   45                 126     28
197         198    Male   32                 126     74
198         199    Male   32                 137     18
199         200    Male   30                 137     83

[200 rows x 5 columns]

In [34]:
datos.reset_index(inplace==True)
datos

NameError: name 'inplace' is not defined

**_Obtene estadistica descriptiva para las columnas que corresponden al salario anual y puntaje de gastos de las personas entre 25 y 40 a√±os. Lo importante es que se muestre promedio, mediana, desvio estandard, valores minimos y maximos._**

In [33]:
clientes_seleccionados[['Spend','Ingresos']].describe()

KeyError: "['Ingresos'] not in index"

ü§î &nbsp; De acuerdo a los valores **_¬øCu√°l es el sueldo promedio de estos clientes? ¬øCual es el puntaje de gastos mediano en el grupo? ¬øCrees que son buenas medidas para caracterizar el grupo?_**

**_Compara estos valores con aquellos de los clientes en general._**

**_Obtiene la edad promedio de clientes que tienen un sueldo mayor al promedio._**

**_Compara estos valores con aquellos de los clientes en general._**

ü§î &nbsp; **_¬øQu√© otras preguntas te surgen para analizar en este dataset?_**

#### VISUALIZA LOS DATOS

**_Visualiza la distribuci√≥n de las variables de sueldo promedio y puntaje de gastos. Haz gr√°ficos que superpongan la distribuci√≥n de cada una de estas variables de manera global como tambi√©n s√≥lo para los clientes seleccionados._**

**_Agrupa los datos por la variable `Genre` para ambos casos. Gr√°fica el ingreso promedio y su dispersion. Grafica, luego, el ingreso mediano y su rango intercuartil._**

ü§î &nbsp; **_¬øExiste una correlaci√≥n entre el sueldo anual y el puntaje de gastos en los clientes seleccionados? ¬øY en todos los clientes en general?_**

**_Visualiza otros datos que creas relevantes para este analisis._**

#### üíæ &nbsp; GUARDANDO EL ARCHIVO PARA LOS SIGUIENTES PASOS

Los siguientes pasos que vamos a tomar implican la transformaci√≥n de los datos presentes en el dataset para un correcto ajuste de un modelo a elecci√≥n. Para no tener que correr nuevamente todo el c√≥digo, podemos guardar en un archivo `csv` el dataset tal cual lo tenemos ahora.

1) **Utiliza la funci√≥n `.to_csv()` para guardar tu dataset**. Antes de hacerlo chequea la [documentaci√≥n](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html).